service: aws-dummy-app
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  memorySize: 128
plugins:
  - serverless-ignore
functions:
  app:
    handler: lib/index.js
    events:
      - http:
          path: /
          method: ANY
          cors: true

      - http:
          path: /{proxy+}
          method: ANY
          cors: true
