service:
  name: aws-dummy-app

plugins:
  - serverless-ignore

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod

functions:
  main:
    handler: lib/index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
