service:
  name: aws-dummy-app

plugins:
  - serverless-ignore

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod

functions:
  mainFunction:
    handler: lib/index.handler
    events:
      - http:
          private: false
          path: /
          method: get
