#!/bin/node

const app = require("./lib").default,
    dotenv = require("dotenv")

dotenv.config()

/* eslint-disable one-var */
const defaultPort = 3333,
    port = process.env.PORT === "default" || !process.env.PORT
        ? defaultPort
        : Number(process.env.PORT)

app.listen(port, () => (
    console.log(`App listening on ${port}!`)
))
