#!/bin/bash

result="$(./dockerBuild)"

if [[ ! "$result" ]]; then
    echo "An error occured"
    exit 1
fi

sudo cp ./build/main ./main

zip function.zip ./main -v

aws lambda update-function-code \
    --function-name todo-post-confirm \
    --zip-file fileb://function.zip
