#!/bin/bash

echo "Entering sudo mode"

if [[ ! "$(sudo docker info)" ]]; then
    echo -e "The docker daemon is not running, would you like to start it?\n [Y/n]"

    read -r startDaemon

    if [[ "$startDaemon" == "y" ]]; then
        sudo dockerd & disown

        # Wait for Daemon to start completely
        sleep 1
    else
        exit 1
    fi
fi

echo "Running docker run"
sudo docker run -it -v "$PWD":/app dummy-aws-app sh -c "cd /app && env GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags '-d -s -w' -a -tags netgo -installsuffix netgo -o ./build/main ./main.go ./handler.go && cp -v ./build/main ./build"

sudo cp ./build/main ./main
